---
ansible_hostname_expected: sandbox-iosxe-latest-1.cisco.com
management_protocols:
  ssh: 22
  netconf: 830
  restconf: 443
report_tags:
  course: CNS4107
  lab: ansible-wsl-devnet
  environment: public-sandbox
